/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Story = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'expiresAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'mediaUrl' : IDL.Text,
  'textOverlay' : IDL.Text,
  'mediaType' : IDL.Text,
  'viewerCount' : IDL.Nat,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadata = IDL.Record({
  'id' : IDL.Nat,
  'creator' : IDL.Principal,
  'contentType' : IDL.Text,
  'externalBlob' : ExternalBlob,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'uploadedAt' : IDL.Int,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'likeCount' : IDL.Nat,
  'thumbnailUrl' : IDL.Text,
  'hashtags' : IDL.Vec(IDL.Text),
  'createdAt' : IDL.Int,
  'shareCount' : IDL.Nat,
  'viewCount' : IDL.Nat,
  'caption' : IDL.Text,
  'commentCount' : IDL.Nat,
  'videoUrl' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'followerCount' : IDL.Nat,
  'followingCount' : IDL.Nat,
  'lastSeen' : IDL.Int,
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'likeCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'author' : IDL.Principal,
  'videoId' : IDL.Nat,
});
export const User = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'isOnline' : IDL.Bool,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'followerCount' : IDL.Nat,
  'passwordHash' : IDL.Text,
  'followingCount' : IDL.Nat,
  'lastSeen' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addVideo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteStory' : IDL.Func([IDL.Nat], [], []),
  'follow' : IDL.Func([IDL.Principal], [], []),
  'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
  'getAllUserids' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getFileById' : IDL.Func([IDL.Nat], [IDL.Opt(FileMetadata)], ['query']),
  'getFilesByCreator' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(FileMetadata)],
      ['query'],
    ),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
  'getOnlineStatus' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
  'getStoryViewCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
  'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getUserPresenceStatus' : IDL.Func([], [IDL.Bool], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersWithActiveStories' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getVideosByCreator' : IDL.Func([IDL.Principal], [IDL.Vec(Video)], ['query']),
  'hasViewedStory' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Bool)], ['query']),
  'likeVideo' : IDL.Func([IDL.Nat], [], []),
  'markStoryViewed' : IDL.Func([IDL.Nat], [], []),
  'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'unfollow' : IDL.Func([IDL.Principal], [], []),
  'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
  'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [FileMetadata],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Story = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'expiresAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'mediaUrl' : IDL.Text,
    'textOverlay' : IDL.Text,
    'mediaType' : IDL.Text,
    'viewerCount' : IDL.Nat,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadata = IDL.Record({
    'id' : IDL.Nat,
    'creator' : IDL.Principal,
    'contentType' : IDL.Text,
    'externalBlob' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'uploadedAt' : IDL.Int,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'likeCount' : IDL.Nat,
    'thumbnailUrl' : IDL.Text,
    'hashtags' : IDL.Vec(IDL.Text),
    'createdAt' : IDL.Int,
    'shareCount' : IDL.Nat,
    'viewCount' : IDL.Nat,
    'caption' : IDL.Text,
    'commentCount' : IDL.Nat,
    'videoUrl' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'followerCount' : IDL.Nat,
    'followingCount' : IDL.Nat,
    'lastSeen' : IDL.Int,
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'likeCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'author' : IDL.Principal,
    'videoId' : IDL.Nat,
  });
  const User = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'isOnline' : IDL.Bool,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'followerCount' : IDL.Nat,
    'passwordHash' : IDL.Text,
    'followingCount' : IDL.Nat,
    'lastSeen' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addStory' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addVideo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteStory' : IDL.Func([IDL.Nat], [], []),
    'follow' : IDL.Func([IDL.Principal], [], []),
    'getActiveStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getAllFiles' : IDL.Func([], [IDL.Vec(FileMetadata)], ['query']),
    'getAllUserids' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getAllVideos' : IDL.Func([], [IDL.Vec(Video)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComments' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getFileById' : IDL.Func([IDL.Nat], [IDL.Opt(FileMetadata)], ['query']),
    'getFilesByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(FileMetadata)],
        ['query'],
      ),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getMyStories' : IDL.Func([], [IDL.Vec(Story)], ['query']),
    'getOnlineStatus' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    'getStoriesByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Story)], ['query']),
    'getStoryViewCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUser' : IDL.Func([IDL.Principal], [IDL.Opt(User)], ['query']),
    'getUserByEmail' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getUserPresenceStatus' : IDL.Func([], [IDL.Bool], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersWithActiveStories' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getVideosByCreator' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Video)],
        ['query'],
      ),
    'hasViewedStory' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'incrementViewCount' : IDL.Func([IDL.Nat], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([IDL.Principal], [IDL.Opt(IDL.Bool)], ['query']),
    'likeVideo' : IDL.Func([IDL.Nat], [], []),
    'markStoryViewed' : IDL.Func([IDL.Nat], [], []),
    'registerUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'unfollow' : IDL.Func([IDL.Principal], [], []),
    'unlikeVideo' : IDL.Func([IDL.Nat], [], []),
    'updateOnlineStatus' : IDL.Func([IDL.Bool], [], []),
    'updateUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [FileMetadata],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };