/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'likeCount' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'author' : Principal,
  'replyToId' : [] | [bigint],
  'videoId' : bigint,
}
export interface ConversationSummary {
  'lastMessageAt' : bigint,
  'lastMessage' : string,
  'otherUser' : Principal,
  'unreadCount' : bigint,
}
export interface DirectMessage {
  'id' : bigint,
  'createdAt' : bigint,
  'text' : string,
  'isRead' : boolean,
  'toUser' : Principal,
  'fromUser' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : bigint,
  'creator' : Principal,
  'contentType' : string,
  'externalBlob' : ExternalBlob,
  'fileName' : string,
  'fileSize' : bigint,
  'uploadedAt' : bigint,
}
export interface Story {
  'id' : bigint,
  'creator' : Principal,
  'expiresAt' : bigint,
  'createdAt' : bigint,
  'mediaUrl' : string,
  'textOverlay' : string,
  'mediaType' : string,
  'viewerCount' : bigint,
}
export interface User {
  'id' : Principal,
  'bio' : string,
  'name' : string,
  'isOnline' : boolean,
  'pinnedVideoIds' : Array<bigint>,
  'email' : string,
  'avatarUrl' : string,
  'followerCount' : bigint,
  'passwordHash' : string,
  'followingCount' : bigint,
  'lastSeen' : bigint,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'isOnline' : boolean,
  'email' : string,
  'avatarUrl' : string,
  'followerCount' : bigint,
  'followingCount' : bigint,
  'lastSeen' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Video {
  'id' : bigint,
  'title' : string,
  'creator' : Principal,
  'likeCount' : bigint,
  'thumbnailUrl' : string,
  'hashtags' : Array<string>,
  'createdAt' : bigint,
  'shareCount' : bigint,
  'privacy' : string,
  'viewCount' : bigint,
  'caption' : string,
  'commentCount' : bigint,
  'videoUrl' : string,
}
export interface VideoInteractionState {
  'likeCount' : bigint,
  'liked' : boolean,
  'shareCount' : bigint,
  'commentCount' : bigint,
  'bookmarked' : boolean,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, [] | [bigint]], undefined>,
  'addStory' : ActorMethod<[string, string, string], bigint>,
  'addVideo' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteStory' : ActorMethod<[bigint], undefined>,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'follow' : ActorMethod<[Principal], undefined>,
  'getActiveStories' : ActorMethod<[], Array<Story>>,
  'getAllFiles' : ActorMethod<[], Array<FileMetadata>>,
  'getAllUserids' : ActorMethod<[], Array<Principal>>,
  'getAllVideos' : ActorMethod<[], Array<Video>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComments' : ActorMethod<[bigint], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getFileById' : ActorMethod<[bigint], [] | [FileMetadata]>,
  'getFilesByCreator' : ActorMethod<[Principal], Array<FileMetadata>>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getMyStories' : ActorMethod<[], Array<Story>>,
  'getOnlineStatus' : ActorMethod<[Array<Principal>], Array<boolean>>,
  'getPinnedVideos' : ActorMethod<[Principal], Array<Video>>,
  'getStoriesByUser' : ActorMethod<[Principal], Array<Story>>,
  'getStoryViewCount' : ActorMethod<[bigint], bigint>,
  'getUser' : ActorMethod<[Principal], [] | [User]>,
  'getUserBookmarks' : ActorMethod<[], Array<Video>>,
  'getUserByEmail' : ActorMethod<[string], [] | [User]>,
  'getUserPresenceStatus' : ActorMethod<
    [Principal],
    [] | [{ 'isOnline' : boolean, 'lastSeen' : bigint }]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideos' : ActorMethod<[Principal], Array<Video>>,
  'getUsersWithActiveStories' : ActorMethod<[], Array<Principal>>,
  'getVideoCount' : ActorMethod<[Principal], bigint>,
  'getVideoInteractionState' : ActorMethod<
    [bigint],
    [] | [VideoInteractionState]
  >,
  'getVideosByCreator' : ActorMethod<[Principal], Array<Video>>,
  'hasViewedStory' : ActorMethod<[bigint], boolean>,
  'incrementViewCount' : ActorMethod<[bigint], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal], boolean>,
  'likeComment' : ActorMethod<[bigint], undefined>,
  'likeVideo' : ActorMethod<[bigint], undefined>,
  'markConversationRead' : ActorMethod<[Principal], undefined>,
  'markStoryViewed' : ActorMethod<[bigint], undefined>,
  'pinVideo' : ActorMethod<[bigint], undefined>,
  'recordShare' : ActorMethod<[bigint], undefined>,
  'registerUser' : ActorMethod<[string, string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], bigint>,
  'toggleBookmarkVideo' : ActorMethod<[bigint], boolean>,
  'toggleLikeVideo' : ActorMethod<[bigint], boolean>,
  'unfollow' : ActorMethod<[Principal], undefined>,
  'unlikeComment' : ActorMethod<[bigint], undefined>,
  'unlikeVideo' : ActorMethod<[bigint], undefined>,
  'unpinVideo' : ActorMethod<[bigint], undefined>,
  'updateOnlineStatus' : ActorMethod<[boolean], undefined>,
  'updateUserProfile' : ActorMethod<[string, string, string], undefined>,
  'updateVideo' : ActorMethod<
    [bigint, string, Array<string>, string],
    undefined
  >,
  'uploadFile' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    FileMetadata
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];